#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/common.sh"

require_cmd curl

OUT_DIR="${REPO_ROOT}/docs/harness_sources"
STAMP="${1:-$(date +%F)}"
OUT_FILE="${OUT_DIR}/${STAMP}-openai-anthropic-meta-harness-refresh.md"

mkdir -p "${OUT_DIR}"

probe_url() {
  local url="$1"
  curl -Ls -o /dev/null -w '%{http_code} %{url_effective}\n' "${url}"
}

read -r OPENAI_HARNESS_STATUS OPENAI_HARNESS_EFFECTIVE <<<"$(probe_url "https://openai.com/index/harness-engineering/")"
read -r OPENAI_CODEX_STATUS OPENAI_CODEX_EFFECTIVE <<<"$(probe_url "https://cdn.openai.com/pdf/6a2631dc-783e-479b-b1a4-af0cfbd38630/how-openai-uses-codex.pdf")"
read -r OPENAI_AGENTS_STATUS OPENAI_AGENTS_EFFECTIVE <<<"$(probe_url "https://cdn.openai.com/business-guides-and-resources/a-practical-guide-to-building-agents.pdf")"
read -r ANTHROPIC_SETTINGS_STATUS ANTHROPIC_SETTINGS_EFFECTIVE <<<"$(probe_url "https://code.claude.com/docs/en/settings")"
read -r ANTHROPIC_SUBAGENTS_STATUS ANTHROPIC_SUBAGENTS_EFFECTIVE <<<"$(probe_url "https://code.claude.com/docs/en/sub-agents")"
read -r ANTHROPIC_HOOKS_STATUS ANTHROPIC_HOOKS_EFFECTIVE <<<"$(probe_url "https://code.claude.com/docs/en/hooks")"
read -r METAHARNESS_PAPER_STATUS METAHARNESS_PAPER_EFFECTIVE <<<"$(probe_url "https://arxiv.org/abs/2603.28052")"
read -r METAHARNESS_SITE_STATUS METAHARNESS_SITE_EFFECTIVE <<<"$(probe_url "https://yoonholee.com/meta-harness/")"
read -r METAHARNESS_REPO_STATUS METAHARNESS_REPO_EFFECTIVE <<<"$(probe_url "https://github.com/stanford-iris-lab/meta-harness")"

cat >"${OUT_FILE}" <<EOF
# Harness Source Snapshot ${STAMP}

Generated by \`scripts/refresh_harness_sources.sh\`.

This file records the source URLs and the HTTP status visible at refresh time. Curated local policy stays under \`docs/harness_standards/\`.

| Source | URL | HTTP status | Effective URL |
| --- | --- | --- | --- |
| OpenAI Harness Engineering | <https://openai.com/index/harness-engineering/> | ${OPENAI_HARNESS_STATUS} | ${OPENAI_HARNESS_EFFECTIVE} |
| OpenAI How OpenAI Uses Codex | <https://cdn.openai.com/pdf/6a2631dc-783e-479b-b1a4-af0cfbd38630/how-openai-uses-codex.pdf> | ${OPENAI_CODEX_STATUS} | ${OPENAI_CODEX_EFFECTIVE} |
| OpenAI A Practical Guide To Building Agents | <https://cdn.openai.com/business-guides-and-resources/a-practical-guide-to-building-agents.pdf> | ${OPENAI_AGENTS_STATUS} | ${OPENAI_AGENTS_EFFECTIVE} |
| Anthropic Claude Code Settings | <https://code.claude.com/docs/en/settings> | ${ANTHROPIC_SETTINGS_STATUS} | ${ANTHROPIC_SETTINGS_EFFECTIVE} |
| Anthropic Claude Code Subagents | <https://code.claude.com/docs/en/sub-agents> | ${ANTHROPIC_SUBAGENTS_STATUS} | ${ANTHROPIC_SUBAGENTS_EFFECTIVE} |
| Anthropic Claude Code Hooks | <https://code.claude.com/docs/en/hooks> | ${ANTHROPIC_HOOKS_STATUS} | ${ANTHROPIC_HOOKS_EFFECTIVE} |
| Meta-Harness Paper | <https://arxiv.org/abs/2603.28052> | ${METAHARNESS_PAPER_STATUS} | ${METAHARNESS_PAPER_EFFECTIVE} |
| Meta-Harness Project Page | <https://yoonholee.com/meta-harness/> | ${METAHARNESS_SITE_STATUS} | ${METAHARNESS_SITE_EFFECTIVE} |
| Meta-Harness Reference Repo | <https://github.com/stanford-iris-lab/meta-harness> | ${METAHARNESS_REPO_STATUS} | ${METAHARNESS_REPO_EFFECTIVE} |
EOF

info "Wrote harness source snapshot ${OUT_FILE}"
